config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  get 'home/about'
  devise_for :users
  resources :friends
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friend
         has_many :post
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :destroy, :update]



  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  def correct_user

    @friend = current_user.friend.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized" if @friend.nil? 

  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend=current_user.friend.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend=current_user.friend.build(friend_params)


    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end 
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index]

  def index
    @posts=Post.all
    # @posts = Post.joins(:user).select('posts.*, users.email as user_email')

  end
  def new
    @post=current_user.post.build
    
  end 

  def create
    # puts Post.all
    # @post = Post.new(title: params[:post][:title])
    @post=current_user.post.build(post_params)

    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% friend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.text_field :first_name, id: :friend_first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :last_name, id: :friend_last_name ,  class:"form-control" , placeholder:"Last Name"%>
  </div>

  <div class="field mb-3">
    <%= form.text_field :email, id: :friend_email,  class:"form-control" , placeholder:"Email" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :phone, id: :friend_phone,  class:"form-control" , placeholder:"Phone" %>
  </div>

  <div class="field mb-3">

    <%= form.number_field :user_id, id: :friend_user_id,  
    class:"form-control", value: current_user.id, type: :hidden%>

  </div>
  


  <div class="actions mb-3">
    <%= form.submit class:"btn btn-success"%>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend ,class:"btn btn-secondary"%> 
<%= link_to 'Back', friends_path  ,class:"btn btn-secondary"%>

app/views/friends/index.html.erb
<h1>Friends</h1>

<table class="table table-striped">
  <thead class="table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>User Name</th>
      <th>User ID</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
        <tr>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          
          <td><%= current_user.email %></td>
          <td><%= friend.user_id %></td>

          <td><%= friend.phone %></td>
          <td><%= link_to 'Show', friend %></td>
          <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
          <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class:"btn btn-primary" %>

app/views/friends/new.html.erb
<h1>New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @friend.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @friend.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @friend.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @friend.phone %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-primary"  %> 
<%= link_to 'Back', friends_path, class:"btn btn-secondary"  %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Application</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Home', root_path, class:"nav-link active"%>
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
        </li>
        <li class="nav-item">
            <%= link_to 'About', home_about_path, class:"nav-link"%>

          <%# <a class="nav-link" href="#">About</a> %>
        </li>
        <li class="nav-item">
            <%= link_to 'Post', posts_path, class:"nav-link"%>

          <%# <a class="nav-link" href="#">About</a> %>
        </li>
        <li class="nav-item">
            <%= link_to 'Create Post', new_post_path, class:"nav-link"%>

          <%# <a class="nav-link" href="#">About</a> %>
        </li>
        
        
        <%if user_signed_in?%>
            <li class="nav-item">
                    <li class="nav-item">
                <%= link_to 'Friends', friends_path, class:"nav-link"%>

            <%# <a class="nav-link" href="#">About</a> %>
            </li>
            <li class="nav-item">
                <%= link_to 'Add Friends', new_friend_path, class:"nav-link"%>

            <%# <a class="nav-link" href="#">About</a> %>
            </li>
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete ,class:"nav-link"%>

            <%# <a class="nav-link" href="#">About</a> %>
            </li>
            <li class="nav-item">
                <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>

            <%# <a class="nav-link" href="#">About</a> %>
            </li>
        <% else%>
            <li class="nav-item">
                <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>

            <%# <a class="nav-link" href="#">About</a> %>
            </li>
            <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class:"nav-link"%>

            <%# <a class="nav-link" href="#">About</a> %>
            </li>
        <%end%>
       
        
        <%# <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> %>
        <%# <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li> %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us-----</h1>

app/views/home/index.html.erb
<h1>HelloWorld</h1>
<%# <p>Find me in app/views/home/index.html.erb</p> %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Application</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header' %> 

    
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts'%>
      
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Friend</h1>

<%# <%= render 'form', friend: @friend %>

<%# <%= link_to 'Show', @friend ,class:"btn btn-secondary"%>
<%# <%= link_to 'Back', friends_path  ,class:"btn btn-secondary"%>

app/views/posts/index.html.erb
<h1>All Posts</h1>


  <div class="container my-5">
  <% @posts.each do |post| %>
    <div class="card mb-4">
      <div class="card-body">
        <h3 class="card-title">
          <%= post.title %>
        </h3>
        <h6 class="card-subtitle mb-2 text-muted">
          <%= post.user.email %>
        </h6>
        <p class="card-text">
          <%= post.content %>
        </p>
      </div>
    </div>
  <% end %>
</div>



<br>

<%= link_to 'Create Post', new_post_path, class:"btn btn-primary" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with(url: posts_path, model: @post, local: true) do |form| %>

  <div class="field mb-3">
    <%= form.text_field :title,id: :Post_title, class:"form-control", placeholder:"Title" %>
  </div>

  <div class="field mb-3">
    <%= form.text_area :content,id: :Post_content,  class:"form-control" , placeholder:"Content"%>
  </div>

  <div class="field mb-3">

    <%= form.number_field :user_id, id: :Post_user_id, 
    class:"form-control", value: current_user.id, type: :hidden%>

  </div>
  


  <div class="actions mb-3">
    <%= form.submit class:"btn btn-success"%>
  </div>
<% end %>